# End-to-end: build a model from data generated by a known system, sample it,
# and check the chain round-trips and recovers the truth.

using Logging

@testset "recovering a known orbit from relative astrometry" begin
    # Span ~1.6 orbital periods: with only a fraction of an orbit observed,
    # eccentricity is genuinely unconstrained and the test would be measuring
    # the prior, not the fit.
    epochs = collect(range(56000.0, 59000.0, length=20))
    truth = PlanetOrbits.System(
        (PlanetOrbits.Body(mass=1.0, name=:A), PlanetOrbits.Body(mass=5mjup, name=:b)),
        (PlanetOrbits.Orbit(PlanetOrbits.Body(mass=5mjup, name=:b),
            about=PlanetOrbits.Body(mass=1.0, name=:A);
            a=3.0, e=0.3, i=0.9, ω=1.2, Ω=2.0, tp=55000.0),); plx=30.0)
    tr = orbitsolve(truth, epochs)
    ra = [raoff(tr[k], :b, :A) for k in eachindex(epochs)]
    dec = [decoff(tr[k], :b, :A) for k in eachindex(epochs)]

    A = Octofitter.Body(name="A", variables=@variables begin
        mass ~ truncated(Normal(1.0, 0.05), lower=0.5)
    end)
    b = Octofitter.Body(name="b", about=A, variables=@variables begin
        mass = 5mjup
        a ~ Uniform(1, 8)
        e ~ Uniform(0, 0.7)
        ω ~ Uniform(0, 2pi)
        i ~ Sine()
        Ω ~ Uniform(0, 2pi)
        tp ~ Uniform(50000, 60000)
    end)
    astrom = RelAstromObs((epoch=epochs, ra=ra, dec=dec,
            σ_ra=fill(1.0, length(epochs)), σ_dec=fill(1.0, length(epochs)));
        target=b, ref=A, name="astrom")
    sys = Octofitter.System(name="fit", bodies=[A, b], observations=[astrom],
        variables=@variables begin plx = 30.0 end)

    model = Octofitter.LogDensityModel(sys; verbosity=0)
    @test model.D == 7
    chain = octofit(Random.Xoshiro(1), model; adaptation=1000, iterations=1000, verbosity=0)

    @test size(chain, 1) == 1000
    # Chain columns are `<owner>_<var>`
    @test haskey(chain, :b_a)
    @test haskey(chain, :A_mass)
    @test mean(chain[:b_a]) ≈ 3.0 rtol = 0.1
    @test mean(chain[:b_e]) ≈ 0.3 atol = 0.1
end

@testset "chain round-trip" begin
    A = Octofitter.Body(name="A", variables=@variables begin
        mass ~ Uniform(0.5, 2.0)
    end)
    b = Octofitter.Body(name="b", about=A, variables=@variables begin
        a ~ Uniform(1, 10)
        e ~ Uniform(0, 0.5)
        i ~ Sine()
    end)
    obs = RelAstromObs((epoch=[57000.0, 57500.0], ra=[100.0, 110.0], dec=[50.0, 40.0],
            σ_ra=[2.0, 2.0], σ_dec=[2.0, 2.0]); target=b, ref=A, name="astrom",
        variables=@variables begin jitter ~ LogUniform(0.1, 10) end)
    sys = Octofitter.System(name="rt", bodies=[A, b], observations=[obs],
        variables=@variables begin plx ~ Uniform(10, 50) end)
    model = Octofitter.LogDensityModel(sys; verbosity=0)

    θ = Octofitter.sample_priors(Random.Xoshiro(7), sys)
    nt = model.arr2nt(θ)
    chain = Octofitter.result2mcmcchain([nt])
    back = Octofitter.mcmcchain2result(model, chain, 1)

    @test back.plx ≈ nt.plx
    @test back.bodies.A.mass ≈ nt.bodies.A.mass
    @test back.bodies.b.a ≈ nt.bodies.b.a
    @test back.observations.astrom.jitter ≈ nt.observations.astrom.jitter

    # And the reconstructed PlanetOrbits system matches what the likelihood saw
    posys = Octofitter.construct_system(model, chain, 1)
    ref = Octofitter.make_ln_like(sys).build(nt)
    @test PlanetOrbits.semimajoraxis(posys, 1) ≈ PlanetOrbits.semimajoraxis(ref, 1)
    @test PlanetOrbits.totalmass(posys) ≈ PlanetOrbits.totalmass(ref)
end

@testset "out-of-domain proposals are rejected quietly, not warned about" begin
    # The regime: a bounded-below variable's inverse transform is
    # `lower + exp(y)`, so an unconstrained proposal beyond y ≈ 709 overflows
    # the mass to `Inf`. Parallel tempering's hot chains reach that routinely —
    # the slice sampler's doubling step alone will — and the model used to
    # answer with a page of stack trace claiming the *hierarchy* was circular,
    # for a plain one-planet system. Two things have to hold: the density is
    # -Inf there, and nothing is logged about it.
    A = Octofitter.Body(name="A", variables=@variables begin
        mass ~ truncated(Normal(1.2, 0.1), lower=0.1)
    end)
    b = Octofitter.Body(name="b", about=A, variables=@variables begin
        mass = 0.0
        a ~ Uniform(1, 10)
        e = 0.1
        i = 0.5
        ω = 0.1
        Ω = 0.2
        tp = 50000.0
    end)
    obs = RelAstromObs((epoch=[57000.0, 57500.0], ra=[100.0, 110.0], dec=[50.0, 40.0],
            σ_ra=[2.0, 2.0], σ_dec=[2.0, 2.0]); target=b, ref=A, name="astrom")
    sys = Octofitter.System(name="quiet", bodies=[A, b], observations=[obs],
        variables=@variables begin plx = 30.0 end)
    model = Octofitter.LogDensityModel(sys; verbosity=0)

    # Priors are listed system-first, then per body: [A_mass, b_a].
    θ_t = model.link([1.2, 3.0])
    @test isfinite(model.ℓπcallback(θ_t))
    θ_bad = copy(θ_t)
    θ_bad[1] = 1000.0                        # mass = 0.1 + exp(1000) = Inf
    @test !isfinite(model.invlink(θ_bad)[1])

    # The prior clamps a non-finite logpdf to a large *finite* floor rather
    # than -Inf (a deliberate choice — see `make_ln_prior_transformed`), so the
    # likelihood really is evaluated here. This is not hypothetical.
    logger = Test.TestLogger(min_level=Logging.Debug)
    val = Logging.with_logger(logger) do
        model.ℓπcallback(θ_bad)
    end
    @test val == -Inf
    @test isempty(filter(r -> r.level >= Logging.Warn, logger.logs))
    # Still diagnosable when you ask for it.
    @test any(r -> r.level == Logging.Debug &&
                   occursin("outside the domain", r.message), logger.logs)

    # Same for the other domain failures a wide prior can reach.
    ln_like = Octofitter.make_ln_like(sys)
    nt = model.arr2nt([1.2, 3.0])
    @test nt.bodies.A.mass == 1.2 && nt.bodies.b.a == 3.0   # the order assumed above
    parabolic = merge(nt, (; bodies=merge(nt.bodies,
        (; b=merge(nt.bodies.b, (; e=1.0))))))
    logger2 = Test.TestLogger(min_level=Logging.Debug)
    @test Logging.with_logger(() -> ln_like(sys, parabolic), logger2) == -Inf
    @test isempty(filter(r -> r.level >= Logging.Warn, logger2.logs))
end

@testset "a = 0 from the prior's own transform is -Inf, not NaN" begin
    # The other end of the same story, and the one that was silent rather than
    # loud. `a ~ Uniform(0, 100)` is a support *with* zero in it: the inverse
    # of the bounded transform is `lo + (hi-lo)·logistic(y)`, and logistic
    # underflows to exactly `0.0` at y ≲ -745. The prior density at the
    # boundary is finite, so nothing rejects the draw — and downstream
    # n = √(GM/a³) was `Inf`, J was `NaN`, every observable was `NaN`, and the
    # log-density came back `NaN`. HMC reads a NaN as a divergence: no error,
    # no warning, just wasted proposals. PlanetOrbits now rejects a ≤ 0 at
    # construction, which routes it through the same quiet -Inf as above.
    A = Octofitter.Body(name="A", variables=@variables begin
        mass = 1.2
    end)
    b = Octofitter.Body(name="b", about=A, variables=@variables begin
        mass = 0.0
        a ~ Uniform(0, 100)          # note the 0: the support includes it
        e = 0.1
        i = 0.5
        ω = 0.1
        Ω = 0.2
        tp = 50000.0
    end)
    obs = RelAstromObs((epoch=[57000.0, 57500.0], ra=[100.0, 110.0], dec=[50.0, 40.0],
            σ_ra=[2.0, 2.0], σ_dec=[2.0, 2.0]); target=b, ref=A, name="astrom")
    sys = Octofitter.System(name="underflow", bodies=[A, b], observations=[obs],
        variables=@variables begin plx = 30.0 end)
    model = Octofitter.LogDensityModel(sys; verbosity=0)

    # Reproduce the *route*, not the destination: go in through the model's own
    # transform from an unconstrained coordinate a sampler can propose, and let
    # it underflow. Nothing here asserts a = 0 directly.
    @test isfinite(model.ℓπcallback(model.link([3.0])))
    θ_underflow = [-800.0]
    @test model.invlink(θ_underflow)[1] === 0.0     # exactly, by underflow

    logger = Test.TestLogger(min_level=Logging.Debug)
    val = Logging.with_logger(logger) do
        model.ℓπcallback(θ_underflow)
    end
    @test val == -Inf
    @test !isnan(val)                               # the actual regression
    @test isempty(filter(r -> r.level >= Logging.Warn, logger.logs))
    @test any(r -> r.level == Logging.Debug &&
                   occursin("outside the domain", r.message), logger.logs)

    # And on the gradient path, which is the one that matters for HMC and the
    # one a naive guard would miss: ForwardDiff orders `Dual`s
    # lexicographically, so `0 < Dual(0.0, 1.0)` is `true` and a guard written
    # against the `Dual` rather than its primal would pass here while
    # rejecting the value call above. (PlanetOrbits guards on `_primal`.)
    if model.∇ℓπcallback !== nothing
        gval, _ = Logging.with_logger(Logging.NullLogger()) do
            model.∇ℓπcallback(θ_underflow)
        end
        @test gval == -Inf
        @test !isnan(gval)
    end
end

@testset "construction failures that are *not* domain failures stay loud" begin
    # The classifier is the whole distinction: a bad proposal is the sampler
    # working, anything else is a defect that must not be swallowed.
    @test Octofitter._is_domain_failure(PlanetOrbits.OrbitDomainError("x"))
    @test Octofitter._is_domain_failure(DomainError(-1.0, "√ of a negative a"))
    @test !Octofitter._is_domain_failure(ErrorException("hierarchy is circular"))
    @test !Octofitter._is_domain_failure(MethodError(sin, ()))
    @test !Octofitter._is_domain_failure(UndefVarError(:oops))

    # A malformed hierarchy is a property of the model, not of a draw, so it
    # surfaces where the model is written rather than mid-chain. Octofitter's
    # own node validation catches the reachable cases outright...
    A = Octofitter.Body(name="A", variables=@variables begin mass = 1.0 end)
    b = Octofitter.Body(name="b", about=A, variables=@variables begin a = 1.0 end)
    dup = Octofitter.Orbit(name="dup", exterior=(b,), about=(A,),
        variables=@variables begin a = 2.0 end)
    @test_throws ErrorException Octofitter.System(name="bad", bodies=[A, b, dup],
        variables=@variables begin end)

    # ...and `LogDensityModel` builds the orbital system once, uncaught, so
    # anything that slips past would still be an error at model-construction
    # time rather than a warning from inside the sampler.
    err = ErrorException("synthetic non-domain failure")
    broken = Octofitter.GeneratedLnLike(_ -> throw(err), (args...) -> 0.0)
    @test_throws "synthetic non-domain failure" begin
        try
            broken.build(nothing)
        catch e
            Octofitter._is_domain_failure(e) || rethrow()
        end
    end
    # while the domain case is let through, exactly as the constructor does it
    quiet = Octofitter.GeneratedLnLike(_ -> throw(PlanetOrbits.OrbitDomainError("e == 1")),
        (args...) -> 0.0)
    @test (try
        quiet.build(nothing)
    catch e
        Octofitter._is_domain_failure(e) || rethrow()
        :swallowed
    end) === :swallowed
end
