# End-to-end: build a model from data generated by a known system, sample it,
# and check the chain round-trips and recovers the truth.

@testset "recovering a known orbit from relative astrometry" begin
    # Span ~1.6 orbital periods: with only a fraction of an orbit observed,
    # eccentricity is genuinely unconstrained and the test would be measuring
    # the prior, not the fit.
    epochs = collect(range(56000.0, 59000.0, length=20))
    truth = PlanetOrbits.System(
        (PlanetOrbits.Body(mass=1.0, name=:A), PlanetOrbits.Body(mass=5mjup, name=:b)),
        (PlanetOrbits.Orbit(PlanetOrbits.Body(mass=5mjup, name=:b),
            about=PlanetOrbits.Body(mass=1.0, name=:A);
            a=3.0, e=0.3, i=0.9, ω=1.2, Ω=2.0, tp=55000.0),); plx=30.0)
    tr = orbitsolve(truth, epochs)
    ra = [raoff(tr[k], :b, :A) for k in eachindex(epochs)]
    dec = [decoff(tr[k], :b, :A) for k in eachindex(epochs)]

    A = Octofitter.Body(name="A", variables=@variables begin
        mass ~ truncated(Normal(1.0, 0.05), lower=0.5)
    end)
    b = Octofitter.Body(name="b", about=A, variables=@variables begin
        mass = 5mjup
        a ~ Uniform(1, 8)
        e ~ Uniform(0, 0.7)
        ω ~ Uniform(0, 2pi)
        i ~ Sine()
        Ω ~ Uniform(0, 2pi)
        tp ~ Uniform(50000, 60000)
    end)
    astrom = RelAstromObs((epoch=epochs, ra=ra, dec=dec,
            σ_ra=fill(1.0, length(epochs)), σ_dec=fill(1.0, length(epochs)));
        target=b, ref=A, name="astrom")
    sys = Octofitter.System(name="fit", bodies=[A, b], observations=[astrom],
        variables=@variables begin plx = 30.0 end)

    model = Octofitter.LogDensityModel(sys; verbosity=0)
    @test model.D == 7
    chain = octofit(Random.Xoshiro(1), model; adaptation=1000, iterations=1000, verbosity=0)

    @test size(chain, 1) == 1000
    # Chain columns are `<owner>_<var>`
    @test haskey(chain, :b_a)
    @test haskey(chain, :A_mass)
    @test mean(chain[:b_a]) ≈ 3.0 rtol = 0.1
    @test mean(chain[:b_e]) ≈ 0.3 atol = 0.1
end

@testset "chain round-trip" begin
    A = Octofitter.Body(name="A", variables=@variables begin
        mass ~ Uniform(0.5, 2.0)
    end)
    b = Octofitter.Body(name="b", about=A, variables=@variables begin
        a ~ Uniform(1, 10)
        e ~ Uniform(0, 0.5)
        i ~ Sine()
    end)
    obs = RelAstromObs((epoch=[57000.0, 57500.0], ra=[100.0, 110.0], dec=[50.0, 40.0],
            σ_ra=[2.0, 2.0], σ_dec=[2.0, 2.0]); target=b, ref=A, name="astrom",
        variables=@variables begin jitter ~ LogUniform(0.1, 10) end)
    sys = Octofitter.System(name="rt", bodies=[A, b], observations=[obs],
        variables=@variables begin plx ~ Uniform(10, 50) end)
    model = Octofitter.LogDensityModel(sys; verbosity=0)

    θ = Octofitter.sample_priors(Random.Xoshiro(7), sys)
    nt = model.arr2nt(θ)
    chain = Octofitter.result2mcmcchain([nt])
    back = Octofitter.mcmcchain2result(model, chain, 1)

    @test back.plx ≈ nt.plx
    @test back.bodies.A.mass ≈ nt.bodies.A.mass
    @test back.bodies.b.a ≈ nt.bodies.b.a
    @test back.observations.astrom.jitter ≈ nt.observations.astrom.jitter

    # And the reconstructed PlanetOrbits system matches what the likelihood saw
    posys = Octofitter.construct_system(model, chain, 1)
    ref = Octofitter.make_ln_like(sys).build(nt)
    @test PlanetOrbits.semimajoraxis(posys, 1) ≈ PlanetOrbits.semimajoraxis(ref, 1)
    @test PlanetOrbits.totalmass(posys) ≈ PlanetOrbits.totalmass(ref)
end
